[stqa-5][TEAM A] As a user I want to make sure the "Find Owner" Navigation leads to the Find Owner page
cgerard321/sqta-project-1 pull request #10
Opened 2019-11-14 16:58 UTC by ariouellette2000

2019-11-14 17:12 UTC, meganedarnaud requested changes
Remove line 124 duplicate dependency tag

2019-11-14 17:22 UTC, meganedarnaud submitted a review, later dismissed

2019-11-17 17:54 UTC, hichambel approved these changes

2019-11-19 15:28 UTC, meganedarnaud approved these changes

2019-11-19 17:18 UTC, merged